/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import telas.Relatorios.RelatorioEmpRealizados;
import telas.Relatorios.RelatorioEmpAtivos;
import telas.Relatorios.RelatoriosACadastrados;
import telas.Relatorios.RelatorioFCadastrados;

/**
 *
 * @author thiag
 */
public class TelasdeRelatorios extends javax.swing.JFrame {

    /**
     * Creates new form TelasdeRelatorios
     */
    public TelasdeRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBVoltar = new javax.swing.JButton();
        jBFerramentasCadastradas = new javax.swing.JButton();
        jBEmpAtivos = new javax.swing.JButton();
        jBRAmigosCadastrados = new javax.swing.JButton();
        jBEmpRealizados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Relatórios");

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBFerramentasCadastradas.setText("Ferramentas Cadastradas");
        jBFerramentasCadastradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFerramentasCadastradasActionPerformed(evt);
            }
        });

        jBEmpAtivos.setText("Empréstimos Ativos");
        jBEmpAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpAtivosActionPerformed(evt);
            }
        });

        jBRAmigosCadastrados.setText("Amigos Cadastrados");
        jBRAmigosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRAmigosCadastradosActionPerformed(evt);
            }
        });

        jBEmpRealizados.setText("Empréstimos Realizados");
        jBEmpRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpRealizadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBVoltar)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEmpAtivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFerramentasCadastradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEmpRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBRAmigosCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBFerramentasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRAmigosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEmpAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEmpRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jBVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal janela = new TelaPrincipal();
        
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBFerramentasCadastradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFerramentasCadastradasActionPerformed
        // TODO add your handling code here:
        RelatorioFCadastrados rferramenta = new RelatorioFCadastrados();
        
        rferramenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBFerramentasCadastradasActionPerformed

    private void jBRAmigosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRAmigosCadastradosActionPerformed
        // TODO add your handling code here:
        RelatoriosACadastrados ramigos = new RelatoriosACadastrados();
        
        ramigos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBRAmigosCadastradosActionPerformed

    private void jBEmpAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmpAtivosActionPerformed
        // TODO add your handling code here:
        RelatorioEmpAtivos reempativos = new RelatorioEmpAtivos();
        
        reempativos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBEmpAtivosActionPerformed

    private void jBEmpRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmpRealizadosActionPerformed
        // TODO add your handling code here:
        RelatorioEmpRealizados reemprealizados = new RelatorioEmpRealizados();
        
        reemprealizados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBEmpRealizadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelasdeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelasdeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelasdeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelasdeRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelasdeRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEmpAtivos;
    private javax.swing.JButton jBEmpRealizados;
    private javax.swing.JButton jBFerramentasCadastradas;
    private javax.swing.JButton jBRAmigosCadastrados;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
